### ISSUE TITLE
Support for multiple folders

### ISSUE THREAD

**Issue by fossil12** [rsrbk/GoSwifty#2]
If I have some folders on the same level and I only want to analyze a certain set of them it would be cool if I could provide a list of paths instead of a single one.

Current workaround: Analyze each folder and sum up the results myself.

**Comment by rsrbk** [comment]
Hey, thanks for the feedback!
Could you share more info about this use case? You have some folders in your project that you want to ignore?

**Comment by fossil12** [comment]
Yes. Folders that contain source code of dependencies I don't want to analyze.

**Comment by raid5** [comment]
Same here. I have a workspace setup with Cocoapods and would like to ignore the `/Pods` directory or just specify a couple directories where my source files live.

**Comment by rsrbk** [comment]
Alright guys, I'll try to code it on the weekends.

**Comment by rsrbk** [comment]
Thanks to @raid5 , the tool now supports multiple folders. Please see updated README :)

**Comment by fossil12** [comment]
Cool. Thank you, @raid5.
