### ISSUE TITLE
Following readme installation option 1 results in: "error: root manifest not found"

### ISSUE THREAD

**Issue by drewbratcher** [rsrbk/GoSwifty#4]
Installation of mint via homebrew went fine, but then I tried to run the following command:
`swift run mint install rsrbk/GoSwifty`

I received the following error:
`error: root manifest not found`

I tried the same with sudo and got the same result.

Checking out the repository and running the same command in the sources directory worked however via:
```
git clone git@github.com:rsrbk/GoSwifty.git
cd GoSwifty  
cd Sources
mint install rsrbk/GoSwifty
```

I think you probably should just add cloning the repo to the Readme steps 😁

**Comment by drewbratcher** [comment]
Actually I think cloning the repo is unrelated, we just need to run:
`mint install rsrbk/GoSwifty`

**Comment by rsrbk** [comment]
Thank you! I'll update the README.
