### ISSUE TITLE
Fails to build with Xcode 13

### ISSUE THREAD

**Issue by kikeenrique** [rsrbk/GoSwifty#8]
Hi,

I'm seeing compilation errors with latests Xcode 13 (official release).

`/Users/enrgar/Library/Developer/Xcode/DerivedData/GoSwifty-cyfcvimjphsgqcayapdaqcesumvh/SourcePackages/checkouts/swift-tools-support-core/Sources/TSCBasic/Await.swift:18:28: Value of type '(@escaping (Result<T, ErrorType>) -> Void) -> Void' has no member 'get'`

I think I could provide a PR soon.

Regards

**Comment by kikeenrique** [comment]
Hi, could you review the PR?
It's just a dependency upgrade for fixing compilation problems.

**Comment by kikeenrique** [comment]
@rsrbk Would it be possible to merge the PR?

**Comment by rsrbk** [comment]
Sorry about that
